version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    build: server/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build: client/
    command: npm run dev
    volumes: 
      - ./client:/code
    ports: 
      - "8080:8080"
    depends_on:
      - server